global:
  scrape_interval: 5s # Scrape often for this demo (usually 15s-1m in prod)

scrape_configs:
  - job_name: 'retail_consumer'
    static_configs:
      # host.docker.internal allows Docker container to talk to your laptop
      # If on Linux, use '172.17.0.1:8000' or your local IP
      - targets: ['host.docker.internal:8000']
